# MQTT Configuration MQTT_HOST=30.30.0.2 MQTT_PORT=1883 MQTT_CLIENT_ID=laravel-mqtt-client
MQTT_CLEAN_SESSION=true MQTT_ENABLE_LOGGING=true MQTT_LOG_CHANNEL=stack # # TLS Configuration
(optional) # MQTT_TLS_ENABLED=false # MQTT_TLS_ALLOW_SELF_SIGNED_CERT=false #
MQTT_TLS_VERIFY_PEER=true # MQTT_TLS_VERIFY_PEER_NAME=true # MQTT_TLS_CA_FILE= # MQTT_TLS_CA_PATH= #
MQTT_TLS_CLIENT_CERT_FILE= # MQTT_TLS_CLIENT_CERT_KEY_FILE= # MQTT_TLS_CLIENT_CERT_KEY_PASSPHRASE= #
Authentication (optional) MQTT_AUTH_USERNAME=puskomnet MQTT_AUTH_PASSWORD=puskomnet123 # # Last Will
Configuration (optional) # MQTT_LAST_WILL_TOPIC= # MQTT_LAST_WILL_MESSAGE= #
MQTT_LAST_WILL_QUALITY_OF_SERVICE=0 # MQTT_LAST_WILL_RETAIN=false # # Timeout Configuration #
MQTT_CONNECT_TIMEOUT=60 # MQTT_SOCKET_TIMEOUT=5 # MQTT_RESEND_TIMEOUT=10 #
MQTT_KEEP_ALIVE_INTERVAL=10 # # Auto Reconnect Configuration (optional) #
MQTT_AUTO_RECONNECT_ENABLED=false # MQTT_AUTO_RECONNECT_MAX_RECONNECT_ATTEMPTS=3 #
MQTT_AUTO_RECONNECT_DELAY_BETWEEN_RECONNECT_ATTEMPTS=0
